### ISSUE TITLE
Go-e Integration stopped providing entities although provided via MQTT

### ISSUE THREAD

**Issue by Phipps78** [syssi/homeassistant-goecharger-mqtt#123] opened 2023-11-15 07:50 UTC
Good morning,

a couple of days ago my Go-e integration stopped populating data in some entities, although the missing data is still provided via MQTT. (Error message in entity "Entity no longer available").
I use some of the entities to feed my Energy dashboard (e.g. sensor.go_echarger_mySN_pgrid).
I tryed to understand the root-cause but can't make it work again, so I hope you guys can help me.

Here's what I tryed and learned:
- I checked my MQTT connection using MQTT Explorer: the data from the missing entities is still being provided from Go-eCharger to MQTT server and i can see how it updates fine
- I restored my daily backup from a day earlier of when I still received data > no change
- I re-installed the Go-e Integration > no change
- I restarted Homeassistant

Here is an overview of which entities are available and which aren't:
![Go-e1](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/138013944/d3956d7b-e0f2-4e95-9ddf-bf25dec30af4)
![go-e2](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/138013944/9c78b5e2-5254-4420-8db4-5df51789604b)
![go-e3](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/138013944/acaeb041-81cf-4b6e-a436-9ce25aa9a715)

Any advice would be greatly appreciated!

Thanks
Philipp

**Comment by freedoc35** [comment] 2023-11-19 08:32
Hi, 
having the same issue. Would be great to have those entities for using in automations.
Looking forward to solution comments
Thanks
Dietmar

**Comment by syssi** [comment] 2023-11-25 15:21
Did you update Home Assistant recently? Please make sure you are using the latest release of this custom component.

**Comment by Phipps78** [comment] 2023-11-26 07:16
Yes, I am updated to 2023.11.3Am 25.11.2023 um 16:21 schrieb Sebastian Muszynski ***@***.***>:﻿
Did you update Home Assistant recently? Please make sure you are using the latest release of this custom component.

**Comment by syssi** [comment] 2023-11-26 07:36
I'm talking about the version of this custom component. Do you use HACS to install third party integrations?

**Comment by stormmurdoc** [comment] 2023-12-10 12:05
Hi, having the same issues. 
Installed the integration via HACS
Version: 0.21.1
Home Assistant Version: 2023.12.1 (core) & 20231208.2 (front-end)

Any advice?

**Comment by AndihX** [comment] 2023-12-19 14:40
I can join the club. All entities in the integration are gone.
MQTT shows data is running fine.
Happened from one day to the other, and i have no clue what is causing this.

**Comment by tuglerxda** [comment] 2023-12-28 08:16
Has anyone resolved the issue?

**Comment by syssi** [comment] 2023-12-28 08:58
In most cases the go-e charger dropped the leading slash of the topic prefix so the integration doesn't pick up the traffic anymore. Please make sure all topics or you go-e charger starts with a `/`.

**Comment by toleabivol** [comment] 2023-12-28 18:00
> Please make sure all topics or you go-e charger starts with a /.

How would one add the "/" prefix if the setting is not available in the mobile app ? 

Firmware v: 042.0
Hardware v: 2
App v: 3.2.11

**Comment by syssi** [comment] 2023-12-28 18:21
Go to the `Internet` view -> Extended settings -> scroll to the bottom (MQTT section). There is a setting called `Prefix`. What's the prefix of your device at the moment?

**Comment by mr-gosh** [comment] 2023-12-28 23:24
> What's the prefix of your device at the moment?

As i have the same Problem I respond here
mine is:
`/go-eCharger/xxxxxx/`

and xxxxxx are the IDs we git from out chargers

**Comment by toleabivol** [comment] 2023-12-29 09:12
> Go to the `Internet` view -> Extended settings -> scroll to the bottom (MQTT section). There is a setting called `Prefix`. What's the prefix of your device at the moment?

I don't have it.
I have the MQTT section but there is no Prefix setting/input field. With `mosquitto_sub` I can see that the topic published is "go-eCharger/xxxxxx/status"

**Comment by mr-gosh** [comment] 2023-12-29 11:55
![IMG_20231229_124150.jpg](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/3028703/9169ba72-5804-4d8a-8642-9e8950d36110)

In my App-Version it looks like this.
And I tried it with and without leading slash.

Funny thing is that everything worked on my old pi. But I moved to a new one and there I can add the devices via its 6-digit s rial and I can see in the mqtt server logs that the device is correctly registered but all entities are created as "unavailable".
What could cause this?

**Comment by syssi** [comment] 2024-02-03 14:15
Is this still an issue? I would like to resolve the issue + get a better understanding what's going on in detail. I must admit it's hard to understand what's the issue in detail and are we all talking about the same thing. :-)

**Comment by AndihX** [comment] 2024-02-03 18:01
In my opinion it is the rx tx to rs485 that is overheating. It could be bad
quality, i am not sure.

lør. 3. feb. 2024 kl. 15.15 skrev Sebastian Muszynski <
***@***.***>:

**Comment by dubtec** [comment] 2024-02-05 10:48
I'm also having the issue. While searching for the root cause, I have observed this 'irregularity' - the charger seems to post MQTT messages into a <white-space parent>/go-eCharger/<ID> topic. This is the default MQTT configuration of the charger and I didn't get any other to work as I've tried renaming the topic in the past without success. 
<img width="371" alt="image" src="https://github.com/syssi/homeassistant-goecharger-mqtt/assets/71098860/e67579d1-37df-4a39-bd27-aa4227805239">

**Comment by dubtec** [comment] 2024-02-05 10:50
This is what my go-eCharger produces when viewed from MQTT Explorer:
<img width="311" alt="image" src="https://github.com/syssi/homeassistant-goecharger-mqtt/assets/71098860/3020197b-f18e-4fed-b38c-beb7115507ac">
I observe that this is different than the other entries as there appears to be an empty white-space parent topic. Unfortunately, I wasn't able to change the MQTT topic in the past.

**Comment by SIMULATAN** [comment] 2024-02-11 19:14
Same problem here, it died 2 months ago.
Apparently, one of the 3 I have randomly started working again on the 1st of February?
Although this could be just a bug since I can't find any data in the history even though I'm pretty sure the integration worked when I first set it up a few months ago.
I just tried re-adding one but it still reports as Unavailable.

![screenshot of the MQTT explorer](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/63104422/964e5d0b-159e-4837-812c-8faeb48e6df8)

**Comment by gerhardvilsecker** [comment] 2024-02-28 09:07
Hello guys,
I newly installed integration today. Experienced same problems reported by all other. Inspired by discussions in this thread I "played around a bit" with prefix when configuring integration. As soon as I used "go-eCharger" without a leading slash (default is: "/go-eCharger") all sensors, buttons etc are working :-). Not sure if reconfiguring is possible. I removed device and configured it new. Now everything is working perfect.

**Comment by dubtec** [comment] 2024-02-28 10:36
I’ve tried that too now also, but didn’t work for me.

The reason is a bit different probably. In the meantime (after the integration hasn’t been working for quite some time already) I’ve changed the name of the charger and the MQTT topic to something much shorter.

Now, when I re-install and am being asked for Serial No., I can provide that, but it’s of no value, because I don’t use the standard naming convention.

For this, but also other scenarios, I think, @syssi, that just asking for the MQTT topic as it’s written in the MQTT settings of go-e App is more straightforward then trying to recreate a logic, which may not even apply in some cases.

Best regards

**Comment by dubtec** [comment] 2024-02-28 14:18
@gerhardvilsecker Again, thanks for Your hint, but it doesn't work if the MQTT topic is not "go-eCharger/123456/", but something simpler say "myCharger".

The configuration-dialog expects the serial number, and apparently this integration uses it to construct the MQTT topic by appending it to the prefix.

**Comment by XionIndigo** [comment] 2024-03-09 07:37
Hi everyone, I am also affected. I have also tried the leading / but it has no effect on me. Actually, no matter what names I tried (with or without special characters) nothing worked. Of course, the changes were made on both sides - Charger and Integration.

**Comment by dubtec** [comment] 2024-03-09 07:58
I actually tried changing / adopting the Python scripts of this integration, auch that it wouldn’t rely on the convention to append the serial to the topic. I managed to revive most entities with this. But since this was just a hack and would probably break the integration for all others there’s no point in trying to merge it back. I also don’t have time / the expertise to make a stable version out of that.

**Comment by mmick08** [comment] 2024-04-20 18:27
> Is this still an issue? I would like to resolve the issue + get a better understanding what's going on in detail. I must admit it's hard to understand what's the issue in detail and are we all talking about the same thing. :-)

As the go-e chargers mqtt prefix is now fully configurable in the app maybe it makes sense to replace the prefix+serial configuration within the integration with the full prefix only.

in my opinion it should not be best practice to expose the serial within your mqtt topics. Instead you should be able to choose something like: go-eCharger/home/ or go-eCharger/carport/

At the moment with the current configuration of the integration you are forced to use serial.

especially in case you have multiple go-e chargers it makes it hard to find the vorrect entities.

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/52581125/20fe6ac7-b6ff-42c8-a550-2d8772a67061)

**Comment by syssi** [comment] 2024-05-25 07:48
Let's close this issue because it's all about a changed `base_topic` over time because of firmware updates or new setups.

**Closed by syssi** 2024-05-25 07:48 UTC

**Comment by dubtec** [comment] 2024-05-25 08:09
@syssi Not sure why you’re closing this as this will only be solved with #148, no?

**Comment by syssi** [comment] 2024-05-25 08:52
This is the short term mitigation of the issue: https://github.com/syssi/homeassistant-goecharger-mqtt/pull/128

But I must admit #148 will resolve the thematic entirely.
