### ISSUE TITLE
go echarger calculating wrong in HA dashboard

### ISSUE THREAD

**Issue by Presl1983** [syssi/homeassistant-goecharger-mqtt#165] opened 2024-07-04 19:57 UTC
Any Ideas - since 08.06.2024 the numbers are completly wrong :/

![image](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/142180290/5eea794c-c968-46b1-9404-66779c3c7d89)

**Comment by Presl1983** [comment] 2024-07-06 07:06
no ideas :(

**Comment by sanchosk** [comment] 2024-07-15 18:58
I have similar issue - suddenly the HA after update to 2024.7.2 shows negative values for charger:
![image](https://github.com/user-attachments/assets/73154f32-347a-4695-be6c-4f223d3702d5)

**Comment by Presl1983** [comment] 2024-07-15 19:01
you have to change the sensor - total energy should work now.

**Comment by sanchosk** [comment] 2024-07-15 19:11
It's a sealed device from go-e, can't do anything about the sensor myself. But I can talk to the guys who do the MQTT integration, perhaps...

**Comment by syssi** [comment] 2024-07-15 19:20
As soon the root cause is known a fix is probably easy but I must admit I didn't understand what's causing the issue.

**Comment by sanchosk** [comment] 2024-07-16 08:07
So, I took the same sensor, it was working for more than year no problem, but since 2024.7 release starts to report minus values for some reason.

**Comment by syssi** [comment] 2024-07-16 08:09
@sanchosk Which firmware version do you use?

**Comment by sanchosk** [comment] 2024-07-16 08:12
56.8, go-e 22kW flex, charge controller firmware version 0.0.1-50

**Comment by syssi** [comment] 2024-07-16 08:13
Do you have any idea when you started using this firmware version? Just to make sure we have to search the root cause at Home Assistant 2024.7

**Comment by sanchosk** [comment] 2024-07-16 08:23
Long time ago - more than 2 months, so the FW version was not updated recently. The only thing I am aware of getting update recently was the HA version bump and the related problems with DB cleanup...

**Comment by sanchosk** [comment] 2024-07-18 19:37
So, it seems the problem is with charger, not with HA.
Today, I managed to track the issue.
In my HA statistics, I can see following data:
 | id | state | sum | metadata_id | created_ts | start_ts | last_reset_ts | human time | 
 | -- | -- | -- | -- | -- | -- | -- | -- | 
 | 7217475 | 38436.39915 | 1153933.26274966 | 1224 | 1721314812.8095 | 1721311200 |   | 2024-07-18 15:00:12 | 
 | 7218360 | 789.3687171 | 1116286.23231676 | 1224 | 1721318412.86148 | 1721314800 |   | 2024-07-18 16:00:12 | 
 | 7219244 | 3345.690755 | 1118842.55435466 | 1224 | 1721322012.83838 | 1721318400 |   | 2024-07-18 17:00:12 | 
 | 7220128 | 3855.948684 | 1119352.81228366 | 1224 | 1721325613.88971 | 1721322000 |   | 2024-07-18 18:00:13 | 
 | 7221011 | 3855.948684 | 1119352.81228366 | 1224 | 1721329212.82819 | 1721325600 |   | 2024-07-18 19:00:12 | 

At around 16:40 my wife arrived and plugged in the car. As of that moment, the state and sum column made a mistake - it seems the WH value is reset and started to count from 0.
This caused HA to "rewind" the data back and consider there was huge negative value - in this case -37kWh of "return back".

Is it possible there is some firmware bug that "forgets" to send also the date reset or something?

**Comment by sanchosk** [comment] 2024-07-18 19:44
@syssi  Is it possible I am using wrong value for HA energy dashboard? I just noticed there are 2 different indicators - one called "Charged energy" that seems to reset with every new charging session. But there is another one, called "Total energy" and this one seems cumulative.
The thing is, I did not change any setting, I am using this sensor long-term in HA. And there was no update to the integration, nor to my charger. My only explanation is that this is something that broke during 2024.07.02 release. Ideas?

**Comment by sanchosk** [comment] 2024-07-19 07:45
I did, surprisingly, HA already had the long-term stats for it even though it was not previously on the dashboard. Thanks!

**Comment by syssi** [comment] 2024-07-19 07:54
Did this resolve your issue? Do you still expect a bug here?

**Comment by sanchosk** [comment] 2024-07-19 07:57
Turns out I cannot close it :( Can you, please, help?

**Closed** 2024-07-19 08:04 UTC
