### ISSUE TITLE
Entity sensor.go_echarger_XXXXXX_wh has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by ckbs1973** [syssi/homeassistant-goecharger-mqtt#141] opened 2024-03-10 14:49 UTC
Logger: homeassistant.components.sensor.recorder
Quelle: components/sensor/recorder.py:301
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:45:10 (1 Vorkommnisse)
Zuletzt protokolliert: 15:45:10

Entity sensor.go_echarger_XXXXXX_wh from integration goecharger_mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 1128.949912 (1128.957705) with last_updated set to 2024-03-10T14:43:24.367267+00:00. Please create a bug report at https://github.com/syssi/homeassistant-goecharger-mqtt/issues

**Comment by syssi** [comment] 2024-05-25 08:34
This is a duplicate of #109.

**Closed by syssi** 2024-05-25 08:34 UTC
Labels: bug
